spring.application.name=u5w2l3WebServiceDatabase
spring.datasource.url=jdbc:postgresql://localhost:5432/u5_w2_l3_WebServerDb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=6543
